Add support for Studienordnung 23
lost-university/web pull request #55
Opened 2024-03-25 17:16 UTC by jeremystucki

2024-03-26 12:58 UTC, jeremystucki commented on src/views/Home.vue
> +const BASE_URL = 'https://raw.githubusercontent.com/lost-university/data/2024/data';
note: this will change after the data PR has been merged

2024-03-30 11:45 UTC, StefanieJaeger requested changes

2024-03-30 11:45 UTC, StefanieJaeger commented on src/views/Home.vue
> +        numberOfMissingModules: Math.max(0, 8 - focus.modules
Please use a constant instead of this magic "8".

2024-03-30 16:06 UTC, StefanieJaeger approved these changes

2024-03-30 16:15 UTC, StefanieJaeger approved these changes

2024-03-30 16:15 UTC, merged